#!python3

from pathlib import Path
import datetime
import os

with open('source auto.tex', 'w') as fout:
    fout.write(f"""\
% File automatically generated by make_source.py
% at {datetime.datetime.now()}.
% Do not edit.


""")
    for folder, _, files in os.walk('source/'):
        for fpath in files:
            path = Path(folder) / fpath
            with open(path, 'r') as f:
                if path.suffix == '.py':
                    lang = 'Python'
                elif path.suffix == '.scala':
                    lang = 'Scala'
                fout.write(f"""
\\lstinputlisting[
    language={lang},
    caption={{{path}}},
    label={{src:{str(path).replace('source/', '')}}}
]{{{path}}}
""")

